name = "HardSphereDynamics"
uuid = "f8c3b98f-145e-45c4-bc39-6fc6ac128922"
authors = ["David P. Sanders <dpsanders@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
